version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    commit-message:
      prefix: 'npm'
      include: 'scope'
    labels:
      - 'npm'
      - 'dependencies'
